import asyncio
import sys
import os
from temporalio.client import Client
from temporalio.worker import Worker

# --- DYNAMIC IMPORT SETUP ---
# We need to import the 'workflow.py' that was JUST generated by the tool.
# It lives in ../output/temporal_workflows
OUTPUT_PATH = os.path.abspath(os.path.join(os.path.dirname(__file__), "../output/temporal_workflows"))
sys.path.append(OUTPUT_PATH)

try:
    # Import the generated class and activities
    from workflow import MasterWorkflow, dbt_run, file_scan
except ImportError:
    print("[ERROR] Could not find 'workflow.py'. Did you run the migration engine first?")
    print(f"        Checked path: {OUTPUT_PATH}")
    sys.exit(1)

async def main():
    print(f"[INFO] Connecting to Temporal Server at localhost:7233...")
    client = await Client.connect("localhost:7233")

    # Create the Worker
    worker = Worker(
        client,
        task_queue="talend-migration-queue",
        workflows=[MasterWorkflow],
        activities=[dbt_run, file_scan],
    )

    print(f"[INFO] Worker started. Listening on 'talend-migration-queue'.")
    print(f"[INFO] Press Ctrl+C to stop.")
    
    # Block and wait for work
    await worker.run()

if __name__ == "__main__":
    try:
        asyncio.run(main())
    except KeyboardInterrupt:
        print("\n[INFO] Worker shutting down.")